networks:
  viridian-network:
    external: true
services:
  oracle:
    image: container-registry.oracle.com/database/free:${ORACLE_VERSION:-latest}
    container_name: "oracle"
    restart: always
    security_opt:
      - label=disable
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "0.0.0.0:1521:1521"
      - "0.0.0.0:5500:5500"
    networks:
      - viridian-network
    environment:
      - ORACLE_PWD=Pass123Word
      - ORACLE_EDITION=FREE
    volumes:
      - ${SOURCE_PERSISTENT_PATH}:/opt/oracle/oradata
