networks:
  viridian-network:
    external: true
services:
  proxy:
    image: acrdiaanlnzndev.azurecr.io/http-proxy:${PROXY_VERSION:-latest}
    command: nginx -g "daemon off;"
    container_name: proxy
    hostname: proxy
    restart: always
    security_opt:
      - label=disable
    ports:
      - "8443:8443"
    networks:
      - viridian-network
    volumes:
      - /data/certs:/data/certs
