services:
  proxy:
    image: acrdiaanlnzndev.azurecr.io/http-proxy:${PROXY_VERSION:-latest}
    command: nginx -g "daemon off;"
    container_name: proxy
    hostname: proxy
    restart: always
    ports:
      - "8081:443"
