DROP TABLE V2PN_PER00.PERMANENT_INDEX CASCADE CONSTRAINTS;
DROP TABLE V2PN_SHR00.STORAGE_PARAMETER CASCADE CONSTRAINTS;
DROP USER FIXITY CASCADE;
DROP USER V2PN_PER00 CASCADE;
DROP USER V2PN_SHR00 CASCADE;


CREATE USER FIXITY IDENTIFIED BY FIXITY;
ALTER USER FIXITY QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO FIXITY;


CREATE USER V2PN_PER00 IDENTIFIED BY V2PN_PER00;
ALTER USER V2PN_PER00 QUOTA UNLIMITED ON USERS;

CREATE USER V2PN_SHR00 IDENTIFIED BY V2PN_SHR00;
ALTER USER V2PN_SHR00 QUOTA UNLIMITED ON USERS;

CREATE TABLE V2PN_PER00.PERMANENT_INDEX (
	ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	FILE_SIZE NUMBER(19,0),
	VERSION NUMBER(10,0),
	STATUS NUMBER(10,0),
	STORED_ENTITY_ID VARCHAR2(255),
	CHECK_SUM_TYPE VARCHAR2(255),
	STORAGE_ID NUMBER(19,0),
	UPDATE_DATE DATE,
	STORAGE_ENTITY_TYPE VARCHAR2(8),
	INDEX_LOCATION VARCHAR2(255),
	CHECK_SUM VARCHAR2(255),
	UPDATE_CHECK_SUM NUMBER(1,0),
	PHYS_CHECK_SUM VARCHAR2(255),
	PHYS_CHECK_SUM_TYPE VARCHAR2(255),
	XSD_VERSIONS VARCHAR2(50),
	CREATED_BY VARCHAR2(255),
	TITLE VARCHAR2(4000),
	CONSTRAINT SYS_C0018560 CHECK ("ID" IS NOT NULL)
);
CREATE INDEX PERMANENTINDEX_STORAGEENTITY ON V2PN_PER00.PERMANENT_INDEX (STORAGE_ENTITY_TYPE);
CREATE INDEX PERMANENTINDEX_S_E_ID ON V2PN_PER00.PERMANENT_INDEX (STORED_ENTITY_ID);
CREATE INDEX PERMANENTINDEX_VERSION ON V2PN_PER00.PERMANENT_INDEX (VERSION);
CREATE UNIQUE INDEX PERMANENT_INDEX_UK_02 ON V2PN_PER00.PERMANENT_INDEX (STORED_ENTITY_ID,VERSION,STORAGE_ENTITY_TYPE);


CREATE TABLE V2PN_SHR00.STORAGE_PARAMETER (
	ID NUMBER(19,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"KEY" VARCHAR2(50),
	VALUE VARCHAR2(4000),
	STORAGE_ID NUMBER(19,0)
);
CREATE INDEX STORAGE_ID_IDX ON V2PN_SHR00.STORAGE_PARAMETER (STORAGE_ID);


GRANT SELECT, INSERT, UPDATE, DELETE ON V2PN_PER00.PERMANENT_INDEX TO FIXITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON V2PN_SHR00.STORAGE_PARAMETER TO FIXITY;
